spring.application.name=auto-shopping-agent

#postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/shopping_agent
spring.datasource.username=smart
spring.datasource.password=smart

#hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

spring.server.port=8080
spring.springdoc.swagger-ui.path=/swagger-ui.html
spring.api-docs.path=/v3/api-docs